server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  default:
    type: "mysql"
    link: "root:root@tcp(127.0.0.1:3306)/prometheus_ext"
    debug: true

logger:
  level : "all"
  stdout: true

