
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
    gen:
        dao:
        - link:  "mysql:root:root@tcp(127.0.0.1:3306)/prometheusx"
          tables:  "user,group,node,rules,config"
          jsonCase: "CamelLower"
    build:
      name:      "promtheusx"
      arch:      "amd64,arm64"
      system:    "linux,windows,darwin"
      mod:       "none"
      cgo:       0
      packSrc:   "resource/i18n,resource/public,resource/template"
      version:   "v1.0"
      output:    "./bin"
      extra:     ""